### ISSUE TITLE
Style the file input field

### ISSUE THREAD

**Issue by kevinmu17** [verbb/formie-theme-configs#5]
### What are you trying to do?

I don't see any possibility to style the file input. Tailwind has a way to do this [See docs](https://tailwindcss.com/docs/hover-focus-and-other-states#file-input-buttons)

### What's your proposed solution?

add something like this to the config?
```css
file: {
    fieldInput: {
        resetClass: true,

        attributes: {
            class: 'block w-full text-sm text-slate-500 file:mr-4 file:py-2 file:px-4 file:rounded-full file:border-0 file:text-sm file:font-semibold file:bg-violet-50 file:text-violet-700 hover:file:bg-violet-100',
        },
    },
},
```
